# Generated by Django 4.1.7 on 2023-02-26 14:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company_logos"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "founded",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("team_size", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founders",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Founders",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="SubTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_tag", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_tags",
                        to="pages.company",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_tags",
                        to="pages.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Tag",
                "verbose_name_plural": "Sub Tags",
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_media", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Social",
                "verbose_name_plural": "Company Socials",
            },
        ),
        migrations.CreateModel(
            name="OpenaiDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", ckeditor.fields.RichTextField(blank=True)),
                (
                    "generated_text",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openai_descriptions",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Description",
                "verbose_name_plural": "Generated Descriptions",
            },
        ),
        migrations.CreateModel(
            name="FounderSocialToSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_media",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founder_socials",
                        to="pages.company",
                    ),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.founder"
                    ),
                ),
            ],
            options={
                "verbose_name": "Founder Social",
                "verbose_name_plural": "Founder Socials",
            },
        ),
        migrations.CreateModel(
            name="AdminNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", ckeditor.fields.RichTextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Admin Notes",
            },
        ),
    ]
