# Generated by Django 4.1.7 on 2023-03-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_remove_foundersocialtosocial_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtag",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtags",
                to="pages.company",
            ),
        ),
        migrations.AlterField(
            model_name="subtag",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtags",
                to="pages.tag",
            ),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="pages.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Regions",
            },
        ),
    ]
